### PR TITLE
Automatical Deployment to Heroku

### LINKED ISSUE #22: Add automatic heroku deployment for a demo preview

### PR DESCRIPTION
**Pull request by Segelzwerg**
This uses the [GitHub Action for Heroku ](https://github.com/marketplace/actions/github-action-for-heroku). 

I'm not entirely sure if we need to create releases?
```
workflow "Deploy to Heroku" {
  on = "push"
  resolves = "release"
}
``` 
@n2o we need to add a secret for `HEROKU_API_KEY` which can be generated by `heroku authorizations:create`. Can you do it as you have supreme privileges?

I duplicated part of the gradle build it won't be triggered on every push or PR but only master pushes.

Fix #22

### CODE REVIEW

**Comment by iTitus** [comment]
This kinda duplicates the check logic from the other tasks.
Can we make it so that this task only runs when all the other tasks succeed?

**Comment by Segelzwerg** [comment]
> This kinda duplicates the check logic from the other tasks.
> Can we make it so that this task only runs when all the other tasks succeed?

Actually I don't know, but I can do some research on it.

**Comment by Segelzwerg** [comment]
I remove the heroku workflow and added a deploy step in the gradle workflow.
The deploy has a conditional so it will only run on master pushes.

**Comment by n2o** [comment]
Why not adding a new yml file which is exclusively for the deployment step? Pushes to master should get deployed.

**Comment by Segelzwerg** [comment]
The idea us, that we want to make sure we only push code that works. In other words is passes the tests and we didn't want to have a workflow which is doing exactly the same thing as the gradle workflow. 
I think @iTitus was right to point that out, because we could think of a working PR but the merge into master causes some trouble.

**Comment by n2o** [comment]
But you are currently only able to push code via pull request. Thus, all of the code is being reviewed. So there is no unchecked code which is being merged into master ;-)

**Comment by Segelzwerg** [comment]
Ok doing in other script is easy. I can do it. Could you set up the heroku secret?

**Comment by n2o** [comment]
Done. https://theshorty.herokuapp.com/

**Comment by iTitus** [comment]
> 
> 
> But you are currently only able to push code via pull request. Thus, all of the code is being reviewed. So there is no unchecked code which is being merged into master ;-)

Fair point!

So just do it on master push with the `branches:` thing

**Comment by n2o** [comment]
image
please keep githubs notes on Secrets in mind. So you can't work on a fork to test this thing. Test it on a different branch first, then change it to `master`

**Comment by iTitus** [comment]
The documentation for actions/heroku is outdated.
But it will just pass its args to the heroku cli.

https://github.com/actions/heroku/pull/6 shows an actual working example.
It uses the docker deployment. We could also use git deployment by executing the commands from https://devcenter.heroku.com/articles/git

**Comment by n2o** [comment]
So the heroku actions repository needs a Pull Request ;-)

**Comment by Segelzwerg** [comment]
I tried a lot of stuff found on the internet. I think for the last try to work @n2o you need to add your mail address as a secret.

But probably the easiest way to deploy is to use the web hook integration suggested by @iTitus. I know this is working, because I used on one of my projects.

> We could also use git deployment by executing the commands from https://devcenter.heroku.com/articles/git

**Comment by Segelzwerg** [comment]
At first it seems to have worked but
image

**Comment by n2o** [comment]
I enabled the automatic deployment directly on heroky. So we do not have to add any code here. Thanks for your help!

**Comment by iTitus** [comment]
Well that's also a possibility :)

**Pull request closed without merging**
